config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'public_recipes/index'
  get 'public_recipes/show'
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root 'foods#index'

  resources :foods # [:index, :destroy, :new, :show]
  get '/users', to: 'foods#index'

  resources :users
  resources :recipe_foods # [:index, :destroy, :new, :show]
  resources :recipes, only: %i[index destroy new create show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, :description, presence: true
  validates :preparation_time, :cooking_time, numericality: { greater_than: 0 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user: current_user)
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="container border m-5 p-3 row">
  <div class="col-4">
    <h2>
      <%= link_to recipe.name, recipe %>
    </h2>
    <%= button_to "REMOVE", recipe, method: :delete %>
  </div>

  <p class="col-8">
    <%= recipe.description %>
  </p>

</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="recipes" class="w-75">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>

<%= link_to "New recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container w-75">
  <h2 class="text-center">
    <%= @recipe.name %>
  </h2>
  <p>
    <strong>Preparation time:
      <%= @recipe.preparation_time %>
    </strong>
  </p>
  <p>
    <strong>Cooking time:
      <%= @recipe.cooking_time %>
    </strong>
  </p>
  <p>
    <strong>Steps go here ... </strong>
  </p>

  <%= link_to "Generate shopping list", general_shopping_lists_index_path %> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
  <% if can? :manage, @recipe %>
    <%= link_to "Add ingredients", new_food_path %>
  <% end %>
  <hr>

<div class="d-flex flex-column d-flex justify-content-center mx-auto" style="width: 80%;">
  <table class="min-w-full bg-white">
    <thead class="p-3 mb-2 bg-secondary text-white">
      <tr class="ml-1">
        <th class="border border-slate-600">Food</th>
        <th class="border border-slate-600">Measurement Unit</th>
        <th class="border border-slate-600">Unit Price</th>
        <th class="border border-slate-600">Action</th>
      </tr>
    </thead>
    <tbody class="text-gray-700">
      <% @recipe.foods.each do |food|%>
        <tr class="odd:bg-red-300">
          <td class="border border-slate-600 text-center"><%= food.name%></td>
          <td class="border border-slate-600 text-center"><%= food.measurement_unit%></td>
          <td class="border border-slate-600 text-center"><%= food.price%></td>
          <td class="border border-slate-600 text-center">
            <%= link_to "Delete", food_path(food), :class => "hover:text-red-600",
            data: {
                    turbo_method: :delete,
                    turbo_confirm: "Do you want to delete #{food.name}?"
                  }%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>


</div>