config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'public_recipes/index'
  get 'public_recipes/show'
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root 'foods#index'

  resources :foods # [:index, :destroy, :new, :show]
  get '/users', to: 'foods#index'

  resources :users
  resources :recipe_foods # [:index, :destroy, :new, :show]
  resources :recipes, only: %i[index destroy new create show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>" class="d-flex flex-row gap-4" >
  <div class="grid grid-rows-1 gap-2 grid-cols-3">
    <strong>Name:</strong>
    <%= food.name %>
  </div>

  <div class="grid grid-rows-1 gap-2 grid-cols-3">
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </div>

  <div class="grid grid-rows-1 gap-2 grid-cols-3">
    <strong>Price:</strong>
    <%= food.price %>
  </div>

  <div class="grid grid-rows-1 gap-2 grid-cols-3">
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </div>

  <div class="grid grid-rows-1 gap-2 grid-cols-3">
    <strong>User:</strong>
    <%= food.user_id %>
  </div>

</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="d-flex flex-column d-flex justify-content-center mx-auto" style="width: 80%;">
  <%= link_to "New food", new_food_path %>
  <table class="min-w-full bg-white">
    <thead class="p-3 mb-2 bg-secondary text-white">
      <tr class="ml-1">
        <th class="border border-slate-600">Food</th>
        <th class="border border-slate-600">Measurement Unit</th>
        <th class="border border-slate-600">Unit Price</th>
        <th class="border border-slate-600">Action</th>
      </tr>
    </thead>
    <tbody class="text-gray-700">
      <% @foods.each do |food|%>
        <tr class="odd:bg-red-300">
          <td class="border border-slate-600 text-center"><%= food.name%></td>
          <td class="border border-slate-600 text-center"><%= food.measurement_unit%></td>
          <td class="border border-slate-600 text-center"><%= food.price%></td>
          <td class="border border-slate-600 text-center">
            <%= link_to "Delete", food_path(food), :class => "hover:text-red-600",
            data: {
                    turbo_method: :delete,
                    turbo_confirm: "Do you want to delete #{food.name}?"
                  }%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Delete this food", @food, method: :delete %>
</div>