config/routes.rb
Rails.application.routes.draw do
  get 'general_shopping_lists/index'
  get 'public_recipes/index'
  get 'public_recipes/show'
  devise_for :users

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  root 'foods#index'

  resources :foods # [:index, :destroy, :new, :show]
  get '/users', to: 'foods#index'

  resources :users
  resources :recipe_foods # [:index, :destroy, :new, :show]
  resources :recipes, only: %i[index destroy new create show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background: #425C81">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">Recipe-App</span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
    aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%= link_to 'Foods', foods_path, :class => 'nav-link'  %>
          <%= link_to 'Recipes', recipes_path, :class => 'nav-link' %>
          <%= link_to 'Public recipes', public_recipes_index_path, :class => 'nav-link' %>
          <%= link_to 'General Shopping list', general_shopping_lists_index_path, :class => 'nav-link' %>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>

          <%= button_to "Logout", destroy_user_session_path, method: :delete, data: { turbo: false }, :class => 'nav-link' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link' %>
          <%= link_to "Log in", new_user_session_path, :class => 'nav-link' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>